# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Pokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poke
  pod 'lottie-ios'
  pod 'SSSwiftUIGIFView'
  pod 'Kingfisher', '~> 6.0'
  pod 'SDWebImageSwiftUI'

end
